logging:
  level:
#    org.springframework.web: DEBUG
    br.com.marcelomalcher: DEBUG

data:
  provincesUrl: https://raw.githubusercontent.com/VivaReal/code-challenge/master/provinces.json
  propertiesUrl: https://raw.githubusercontent.com/VivaReal/code-challenge/master/properties.json